version: "3"

volumes:
    postgres_data:

services:
    django:
        build: ./api
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./api:/usr/src/api
        ports:
            - 8000:8000
        env_file:
            - ./config/.env.django.dev
        depends_on:
            - djangodb

    djangodb:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=bounce
            - POSTGRES_PASSWORD=bounce
            - POSTGRES_DB=bounce_dev

    # Nuxt frontend app
    nuxt:
        build: ./client/
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/client
        command:
            "npm run dev"